### ISSUE TITLE
Api not working via http anymore

### ISSUE THREAD

**Issue by tsurai** [Hexagenic/wanikaniwallpaper#10]
The WK api doesn't work via http anymore and returns a 302 code redirecting to its https version. A 302 response is a vaild answer and curl doesn't throw an error but instead returns an empty string instead which libjson can't parse.
Simply using https instead fixes this error.

**Comment by Hexagenic** [comment]
Fixed in d68fd032c43b17f0ea0cdf22f04915a97821ba34
