### ISSUE TITLE
Segmentation fault in renderer.cpp

### ISSUE THREAD

**Issue by tsurai** [Hexagenic/wanikaniwallpaper#11]
I'm getting a segmentation fault at renderer.cpp:73
No idea how you are handling all the rendering stuff so I didn't play around there to not make things worse.

**Comment by wekateka** [comment]
I think I have the same problem, attached is a trace from gdb.

[http://pastebin.com/5u3bdqGT](http://pastebin.com/5u3bdqGT)

**Comment by pkutzner** [comment]
I have the same problem.  I re-compiled with debugging symbols.  Here's the same gdb trace as @wekateka above, but with debugging symbols compiled in.

http://pastebin.com/8CP72633

**Comment by kyrias** [comment]
Yeah, it's getting its math wrong somewhere, trying to write glyphs way outside the buffer, hmm.

**Comment by Hexagenic** [comment]
The two-year anniversary was a couple of weeks ago, I think it's time I dug into it properly once and for all.

**Comment by Mrowqa** [comment]
I have same problem. Checked using gdb.

**Comment by kyrias** [comment]
Heh, three-year anniversary came and passed. ;)

**Comment by Mrowqa** [comment]
Maybe this case will be better than [this one](https://bitbucket.org/site/master/issues/589/file-history-should-follow-copies-and) ;) Who does want to be a hero and fix this? :D

**Comment by Hexagenic** [comment]
Sorry I haven't been active on github for a while. Work has been pretty stressful and so I haven't programmed much on my free time lately. There is a version 2 coming for this project, which will be a major rewrite. I'm hoping to get an alpha out for v2 this weekend, if all goes well.

**Comment by Hexagenic** [comment]
Fixed in f2c6967

**Comment by Mrowqa** [comment]
It works now. Thank you! 😃
